Samples/SimpleAlgorithms/SimpleAlgorithms.qs
This PR fixes a typo in the comments for the SimpleAlgorithms sample project, and normalizes `\t` characters to spaces.
=> Fixed typo in SimpleAlgorithms.

Samples/H2SimulationGUI/package-lock.json, Samples/H2SimulationGUI/package.json, Samples/PythonInterop/environment.yml
Updating version of chart.js as one of its dependencies has a known vulnerability (on server applications, so it doesn't affect us). 
Fixing location of qsharp's python channel to match build version, so updates to latest doesn't break it.
=> Small version updates.

.travis.yml
This PR updates the version of GCC installed on the Travis CI build image such that the correct GNU OpenMP implementation is available to the simulator runtime. This allows the the Linux builds to successfully complete, so the PR also enables Travis CI testing on both macOS and Linux.
=> Update GCC on Travis CI to enable Linux build.

LibraryTests/CombinatorTests.qs, Microsoft.Quantum.Canon/Combinators/CControlled.qs
Added new function and operation with unit tests.
=> Adding CControlled function to the cannon, w/ unit tests.

Microsoft.Quantum.Canon/Microsoft.Quantum.Canon.csproj
The flag went missing when we migrated to .net core. We needed to generate API docs.
=> Adding RunQDocGen flag to Canon

Microsoft.Quantum.Canon/Simulation/Algorithms.qs, Microsoft.Quantum.Canon/Simulation/PauliEvolutionSet.qs, Microsoft.Quantum.Canon/Simulation/Techniques.qs
Relative paths are not supported for xref links.
The correct way is to use the docset name.
=> Fixing links to xref docs

LibraryTests/SimulatorTestTargets.cs
Fix for #62
Space in the class name accidently made the test use a random value instead of using the fixed value required for the test.
=> Fix for #62: RobustPhaseEstimationTest is flaky

Samples/Qiskit/Driver.cs, Samples/Qiskit/Qiskit.csproj, Samples/Qiskit/QiskitInterface.py, Samples/Qiskit/requirements.txt
Upgrade to the latest interface (which doesn't always give an expected queue size).
=> Update to latest IBMQuantumExperience interface

Samples/src/OrderFinding/OrderFinding.csproj, Samples/src/OrderFinding/OrderFinding.qs, Samples/src/OrderFinding/Program.cs, Samples/src/OrderFinding/README.md, Samples/src/ReversibleLogicSynthesis/ReversibleLogicSynthesis.qs
This is an implementation of the order-finding algorithm described in the paper by L.M.K. Vandersypen, M. Steffen, G. Breyta, C.S. Yannoni, R. Cleve, and I.L. Chuang in [Experimental realization of an order-finding algorithm with an NMR quantum computer](https://doi.org/10.1103/PhysRevLett.85.5452), *Phys. Rev. Lett.* **85**, 5452, 2000.
It needs to realize a permutation with different exponents in the quantum circuit. The algorithm makes use of the `PermutationOracle` from the `ReversibleLogicSynthesis` project for this purpose. It also uses `QFT` from the canon.
The quantum algorithm is implemented for general permutation sizes (2ⁿ elements), however, the classical post-processing in the C# file is restricted to permutations over 4 elements.
I needed to make a small update to …
=> Order finding quantum algorithm

Chemistry/MolecularHydrogen/HydrogenSimulation.qs, Samples/src/UnitTesting/CCNOTCircuits.qs, Samples/src/UnitTesting/CCNOTCircuitsTests.qs, Samples/src/UnitTesting/ControlledSWAP.qs, Samples/src/UnitTesting/MultiTargetCNOT.qs, Samples/src/UnitTesting/MultiTargetCNOTTests.qs, Samples/src/UnitTesting/RepeatUntilSuccessCircuits.qs, Samples/src/UnitTesting/Teleportation.qs, Samples/tests/SampleTests/BitFlipTests.qs
This PR cleans up the unit testing sample using the new features of Q# 0.6 (e.g.: removes redundancy, makes use of improved library routines, etc.).
=> Clean up unit testing sample using 0.6 features

Samples/src/Teleportation/host.py
run "print(qsharp.get_workspace_operations())" get the package Microsoft.Quantum.Samples.* not Microsoft.Quantum.Example.*. 
Otherwise get the error: ModuleNotFoundError: No module named 'Microsoft.Quantum.Examples'
=> fix incorrect package name

Dockerfile
After fixing the `iqsharp-base` image to resolve #220 (see microsoft/iqsharp#27), Binder kept a copy of the old image, such that #220 persisted. This PR forces Binder to update to the newly-deployed image by specifying the SHA256 digest of the image instead of its tag. See https://mybinder.org/v2/gh/Microsoft/Quantum/cgranade/docker-sha for an example of Binder running against this PR.
=> Fix #220 by specifying image SHA sum in Dockerfile 

Samples/src/ReversibleLogicSynthesis/ReversibleLogicSynthesis.qs, Samples/tests/SampleTests/ReversibleLogicSynthesisTests.qs
This PR simplifies the code by making use of newer API functions, such as `RangeAsIntArray` and `IndexRange` as well as `for` loops over array elements instead of array indices.
=> Simplifies code for reversible logic synthesis sample

samples/algorithms/chsh-game/README.md, samples/algorithms/simple-grover/README.md, samples/characterization/phase-estimation/README.md, samples/getting-started/intro-to-iqsharp/README.md, samples/getting-started/measurement/README.md, samples/getting-started/simple-algorithms/README.md, samples/getting-started/teleportation/README.md
Links under Manifest aren't working correctly in [samples explorer](https://docs.microsoft.com/en-us/samples/microsoft/quantum/simple-quantum-algorithms/). This change should fix that.
=> dotnetcli identifier and fix broken link

samples/algorithms/oracle-synthesis/OracleSynthesis.qs
This PR removes one function that is now in the Q# libraries and simplifies two arrays, which were unnecessary extended to larger sizes.
=> Simplify code in OracleSynthesis

samples/runtime/state-visualizer/StateVisualizer.cs, samples/runtime/state-visualizer/websrc/app.ts, samples/runtime/state-visualizer/websrc/index.html
Just a few bug fixes for things I found while writing my Q# Advent Calendar post about the state visualizer:
1. There was something wrong with the serialization of operation return values (unit appeared in JavaScript as `{qubits: null}`, and `One` and `Zero` were both `{}` for some reason). I convert them to strings before sending them to the web client now.
2. Fixed a bug where log messages did not cause the timeline to scroll down when they were added (they were missing an element with the `operation-name` class).
3. Removed a period that was at the end of the page title. :)
=> Minor bug fixes for the state visualizer sample

.devcontainer/devcontainer.json, .github/workflows/main.yml, Build/images/samples/Dockerfile, Dockerfile, careers.md
This PR sets up a new GitHub Action to prebuild the Docker image for the samples repo and publish it to the packages feed for this repo.
=> Create new Docker publishing workflow.

.github/workflows/main.yml
This PR delays updating the special `★binder` branch until the Docker image has successfully been replicated to mcr.microsoft.com, polling the MCR catalog until the relevant tag appears. By default, the poll is set to a 30 second interval, relying on GitHub Actions' timeout to terminate the workflow if there is a problem.
=>  Delay updating binder until MCR image is available.

.github/workflows/main.yml
This fixes the issue with GitHub Actions not publishing updates to the `★binder` branch by waiting for the right manifest to appear on mcr.microsoft.com rather than looking at the list of tags. This is needed as mcr.microsoft.com now caches the list of tags behind a CDN, such that it is updated well after the image is available for pulling into Binder.
=> Wait for manifest rather than CDNed tag.

samples/machine-learning/half-moons/Host.cs, samples/machine-learning/half-moons/data.json, samples/machine-learning/half-moons/host.py, samples/machine-learning/wine/host.py
This PR adds Python hosts for the QML samples. Note that these hosts rely on the beta packages hosted on the prerelease feed, and thus will require NuGet.Config changes until the final QML release.
=> Add Python hosts to QML samples

samples/arithmetic/AdderExample.ipynb
Inclusion of Jupyter notebook code snippets into docs require name meta data in the cell that is being referenced. Testing that here.
=> Add name meta data to test inclusion of jupyter notebooks in code

samples/characterization/phase-estimation/README.md
For a bit of context, I was searching for "iterative phase estimation" and this sample was both the first result (docs view) and the third one (GitHub view), but it doesn't point to the relevant page in our docs. It seems like including such link would be a good idea.
=> Add link to iterative phase estimation docs to sample readme

README.md
This PR just updates the MyBinder link in the main README.md file to point to the ⭐binder branch. I've verified that navigating to [this new link](https://mybinder.org/v2/gh/Microsoft/Quantum/⭐binder) pulls the correct image and results in good performance when opening a notebook. The 'Kernel Ready' message appears in about 5 seconds, and then initial execution of a Q# code cell takes only a few seconds.
=> Update Binder link in README.md

Build/clean.ps1, Build/set-env.ps1
This PR uses more explicit paths and build configurations when cleaning to make sure that clean steps match build steps.
=> Improve clean.ps1 to be a bit more robust.

samples/interoperability/qrng/README.md, samples/machine-learning/half-moons/README.md, samples/machine-learning/parallel-half-moons/README.md, samples/machine-learning/wine/README.md
I changed the H1 headers of some duplicated samples. I think it is better than adding a URL but keeping the same names since they would be difficult to discern from the samples browser.
Also uncommented some TODOs of the metadata and body. This is the first try to solve the metadata issues that are breaking the samples pipeline.
=> Some fixes to samples headers and metadata

build.yml
Switching QDK pipeline to use latest images for build agents. There are corresponding PRs in other repos as well.
=> Switch to latest images for build agents

build.yml
This PR sets IQ# HostingEnvironment to "build-agent" in order to identify telemetry coming from CI processes.
=> Set IQ# HostingEnvironment to "build-agent"

samples/runtime/reversible-simulator/Simulator.cs
I think that using the extension method `ToResult()` makes the code easier to read.
=> Use extension method to simplify code in simple reversible simulator

samples/diagnostics/unit-testing/CCNOTCircuitsMetrics.cs
This PR updates the CCNOTCircuitMetrics sample to avoid using APIs deprecated with Q# 0.6, solving some outstanding warnings.
=> Update CCNOTCircuitMetrics to avoid deprecation.

samples/runtime/qpic-simulator/intrinsics/Library.qs, samples/runtime/qpic-simulator/intrinsics/intrinsics.csproj, samples/runtime/qpic-simulator/simulator/Formatter.cs, samples/runtime/qpic-simulator/simulator/Processor.cs, samples/runtime/qpic-simulator/simulator/RewriteStep.cs, samples/runtime/qpic-simulator/simulator/Simulator.Barrier.cs, samples/runtime/qpic-simulator/simulator/Simulator.SavePicture.cs, samples/runtime/qpic-simulator/simulator/Simulator.cs, samples/runtime/qpic-simulator/simulator/simulator.csproj
This PR implements a C# library containing a custom `ICustomProcessor`-based Q# simulator to dump Q# program execution traces into qpic files. It does not support all intrinsic operations and is used as accompanying sample to the 3rd Q# blog post on custom simulators. It also contains an `intrinsics` project with custom Q# operations for the simulator.
There is a lot of code this time, so I created a feature branch. Two upcoming PRs will add (i) a Q# test project with sample code to create qpic pictures and (ii) README and meta data for the sample.
=> IQuantumProcessor sample for qpic output

samples/runtime/state-visualizer/README.md
It probably makes sense to link to the blog post, since it's the most detailed documentation we have for this sample.
=> Add link to blog post to state-visualizer readme

samples/simulation/h2/gui/package-lock.json
Updated electron to 7.2.4, which is the minimum suggested version.
=> Updating electron version for H2 simulation

.gitattributes
By default, [Linguist classifies the `samples` folder as documentation](https://github.com/github/linguist/blob/master/lib/linguist/documentation.yml#L33), meaning it is not counted in the repository's language stats. This PR overrides that classification and fixes the language stats.
Before:
After:
=> Remove linguist-documentation attribute from samples folder

binder-index.md, samples/diagnostics/README.md, samples/diagnostics/dumping/Dumping States and Operations.ipynb, samples/diagnostics/facts-and-assertions/Facts and Assertions.ipynb, samples/diagnostics/visualization/README.md, samples/diagnostics/visualization/Visualizing Quantum Programs.ipynb
This PR adds a sample Q# notebook demonstrating `%trace` and `%debug`, along with some `DumpOperation` and `DumpRegister` examples. I know there are already `Dump` examples in another sample, but it seemed logical to me to include some here as well.
I have also updated the other diagnostics notebooks by removing the `%package Microsoft.Quantum.Standard.Visualization` cell, which is no longer necessary with recent IQ# releases, and re-running the notebooks on the latest release.
=> Add visualization sample for %trace and %debug

Build/images/samples/Dockerfile
Looks like #437 contained an inadvertent change to `Dockerfile` that broke the Docker image build.
e.g., from https://github.com/microsoft/Quantum/runs/1383424059:
```
Step 1/10 : FROM mcr.microsoft.com/quantum/iqsharp-base:0.13.201118141-beta
manifest for mcr.microsoft.com/quantum/iqsharp-base:0.13.201118141-beta not found: manifest unknown: manifest tagged by "0.13.201118141-beta" is not found
Error response from daemon: No such image: public/quantum/samples:77b68faa38df8a601ba3fcc1ffef3094be242cba
```
This change reverts back to use the previously-released version 0.13.20102604.
=> Restore valid base image version

Build/images/samples/Dockerfile
Docker image builds in this repo have started failing with the message:
```
Step 5/10 : RUN dotnet tool install --global PowerShell
---> Running in f061533eb52b
error NU1202: Package PowerShell 7.1.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1) / any.
Package PowerShell 7.1.0 supports: net5.0 (.NETCoreApp,Version=v5.0) / any
The tool package could not be restored.
```
For example, see: https://github.com/microsoft/Quantum/runs/1476769834
This PR pins the PowerShell package version to 7.0.3, which is the latest version based on .NET Core SDK 3.1. The released IQ# base image currently installs only .NET Core SDK 3.1 (see the [IQ# Dockerfile here](https://github.com/microsoft/iqsharp/blob/eddc4175aa8df125be440aa9c28b47e7710471b1/images/iqsharp-base/Dockerfile#L50)).
=> Fix Docker image build by pinning pwsh version to avoid .NET SDK incompatibility

NuGet.config
Revert NuGet.config change as it introduced a break into end to end builds that wasn't caught by PR validations.
=> Revert "Update NuGet.config (#469)"

Build/build.ps1
This PR disables documentation generation in the samples repo entirely. Since the Microsoft.Quantum.Sdk package turns on documentation generation when either `QSharpDocsGeneration` is `true` _or_ when a specific documentation output path is given, setting a path was causing docs generation to turn on.
=> Disable documentation generation in samples.

.github/workflows/checks.yml, samples/algorithms/algorithms.sln, samples/algorithms/sudoku-grover/ColoringGroverWithConstraints.qs, samples/error-correction/error-correction.sln, samples/machine-learning/machine-learning.sln, samples/runtime/runtime.sln
As reported offline by @tcNickolas, a minor typo in a recent update to the Sudoku sample was not caught by our CI process as the sample project was incorrectly omitted from the relevant solution file. This PR:
- Fixes the typo.
- Adds the sudoku sample to the relevant sln file.
- Adds a new CI check to ensure all projects belong to at least one solution.
Note that this PR will **fail** as is, since there are other projects that fail the new check. Once CI has run and identified these projects, I will update the PR accordingly.
=> Fix typo in Sudoku sample

.gitignore, Build/build.ps1
Finally landed at a workaround that actually works, as seen in this e2e build: https://dev.azure.com/ms-quantum-public/Microsoft%20Quantum%20(public)/_build/results?buildId=26386&view=results. This will work for the time being and we can refine/update as we adjust the behavior of Qir Generation and libraries going forward.
=> Workaround for QIR generation in e2e builds

binder-index.md, samples/algorithms/chsh-game/host.py
There is a small typo in samples/algorithms/chsh-game/host.py.
Should read `inputs` rather than `inpus` and  `together` instead of `togther`
Fixes #451
=> Fixed simple typo in the docs

binder-index.md
Link for Grover's Search in the Azure Quantum Service section pointed to Parallel QRNG, not Grover's. Updated to point to Grover's README.
=> Updated README link

samples/azure-quantum/grover/README.md, samples/azure-quantum/hidden-shift/README.md, samples/azure-quantum/ising-model/README.md, samples/azure-quantum/parallel-qrng/README.md
@KittyYeungQ
Teleportation sample is exclude since it's not compatible with IonQ.
Also update certain sample inputs as follows:
- grover: `--n-qubits` 4 doesn't run on Honeywell, change to 3 (too many qubits, 7 in total)
- hidden-shift: `--n-qubits` avoid confusion in regards to which input is used in the cost estimate, simulator (4) or AQ (3), make both 3
=> Add IonQ cost to Azure Quantum samples

Build/images/samples/Dockerfile
Microsoft security recommendations updated to require PowerShell version 7.1.4
=> Upgrade Powershell to 7.1.4

Build/images/samples/Dockerfile
Update the base image to the version produced by the last release to pick up a new security patch.
=> Use latest base image

Chemistry/Schema/README.md, Chemistry/Schema/requirements.txt, Chemistry/Schema/validator.py
The installation instructions for the schema validator were incomplete:
* the click dependency was missing
* the validator script actually does not work with pyyaml
This commit adds a `requirements.txt` file that can be used to install
the requirements in one line.
=> fix: validator installation instructions

Chemistry/Schema/README.md, samples/chemistry/LithiumHydrideGUI/LithiumHydrideGUI.csproj, samples/chemistry/MolecularHydrogenGUI/MolecularHydrogenGUI.csproj, samples/simulation/h2/gui/H2SimulationGUI.csproj
The `Azure.Quantum.Client` from the `Q# runtime` repo has been updated to use the latest `Newtonsoft.Json` package `13.0.1`.
Some samples had references directly to `Azure.Quantum.Client` or the `Microsoft.Quantum.Simulators` (which uses `Azure.Quantum.Client`) and they were also referencing to an older version of `Newtonsoft.Json`, causing a build failure.
This PR fixes the samples by bumping them to the latest `Newtonsoft.Json` and unblocks https://github.com/microsoft/qsharp-runtime/pull/904
Manual tests of affected projects:
**MolecularHydrogenGUI**
**LithiumHydrideGUI**
**H2SimulationGUI**
=> Use latest Azure Quantum .NET SDK and Newtonsoft.Json packages

samples/azure-quantum/parallel-qrng/ParallelQrng.ipynb
In a standalone notebook, it may not make sense to reload the workspace. Removing from sample.
=> Remove workspace reload from Parallel QNRG sample for notebooks

samples/getting-started/simulation/LargeSimulation.ipynb
AQ gallery has a different renderer that handles Esc-sequences unexpectedly. Fixing.
=> AQ gallery renderer fix.

global.json, samples/algorithms/integer-factorization/README.md, samples/getting-started/simulation/LargeSimulation.ipynb
Changes on .Net 6.0.300 requires that a local global.json includes the version of the Quantum.Sdk otherwise projects that don't have it specified fail compilation, even if there is another global.json in their parent path.
=> Adding global.json

samples/azure-quantum/hidden-shift-gallery/hidden-shift.ipynb
Fix a bug in the commented out code of the sample ("circuit" should be => "circ")
=> Fix wrong circuit reference in commented out code

samples/algorithms/sudoku-grover/ColoringGroverWithConstraints.qs, samples/algorithms/sudoku-grover/Program.cs, samples/algorithms/sudoku-grover/Sudoku.qs, samples/algorithms/sudoku-grover/SudokuQuantum.cs
This pull request optimizes the Grover's search Sudoku sample by encoding constraints into search space minimizing required quantum computation and increasing 0 component of state space.
This change allows enables us to also switch over to the sparse simulator ultimately resulting in greatly increased performance. We now have the ability to solve the puzzle [1] on a regular laptop correctly within about 45min requiring 150 iterations, whereas the previous version estimates to require 804 iterations and does not complete in reasonable time.
The difference in [2] is even more significant, the proposed change solves the puzzle instantly with 0 iterations, whereas the current version estimates to require 205887 iterations.
[1]: 
```csharp
{
{ 0,7,3, 8,0,0, 5,1,2 },
{ 9,0,2, 7,0,5, 4,8,6 },
{ …
```
=> Optimize Grover's Search Sudoku Sample

Build/qdk-tools.psm1, Build/test.ps1
Recent builds have started to run out of space again, so this change mimics the space saving tricks used during build on the test and tools invocation parts of the CI pipeline.
=> More space saving tricks in CI scripts

samples/azure-quantum/hello-world/HW-quantinuum-cirq.ipynb
With latest cirq 1.0.0, the result when using the QDK is empty if not providing a key in the measure command.
=> Add key in measure function for cirq+quantinuum

samples/algorithms/noisy-dj/Deutsch–Jozsa with Noise.ipynb, samples/azure-quantum/hello-world/HW-quantinuum-cirq.ipynb
- Fixes links to be absolute links so they work from Azure.
- Specifies a key for the cirq measure() command so that measurements are not empty
=> Small sample fixes for Azure Hosted Notebooks

samples/azure-quantum/hello-world/HW-quantinuum-qsharp.ipynb
This PR reverts the name of the .NET provider back Microsoft.Quantum.Providers.Honeywell that was changed in #728, since this is an internal code that will be remain with the Honeywell name.
=> Revert .NET provider package name to Microsoft.Quantum.Providers.Honeywell

.github/workflows/omnisharp.json
Upgrade the csx file for CI script to run using dotnet 6 instead of dotnet 5, since dotnet 5 is EOL.
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
=> Update csx formatter project to use dotnet6.0

samples/interoperability/dotnet/qsharp/qsharp.csproj, samples/interoperability/python/python-qsharp-interop.ipynb, samples/interoperability/python/python.csproj, samples/runtime/qpic-simulator/simulator/simulator.csproj
DevOps 48463, 48471.
The `netstandard2.1` target framework has undesirable dependencies, migrating the affected packages to `net6.0`.
Multi-repo PR:
[Q#Compiler](https://github.com/microsoft/qsharp-compiler/pull/1601), [Q#RT](https://github.com/microsoft/qsharp-runtime/pull/1121), [iQ#](https://github.com/microsoft/iqsharp/pull/760), [QuantumLibraries](https://github.com/microsoft/QuantumLibraries/pull/656), [Quantum-NC](https://github.com/microsoft/Quantum-NC/pull/84), [Quantum](https://github.com/microsoft/Quantum/pull/771) (samples), [Katas](https://github.com/microsoft/QuantumKatas/pull/868), QDK, and a private repo.
PR CI build can fail, but overall qdk.release (0.27.254480) has succeeded.
=> Fixing the undesirable dependencies issue for qdk

samples/azure-quantum/hello-world/HW-quantinuum-cirq.ipynb, samples/azure-quantum/hello-world/HW-quantinuum-qiskit.ipynb, samples/azure-quantum/hello-world/HW-quantinuum-qsharp.ipynb
update number of qubits for H1-2 and add H2-1 targets in Quantinuum hello,world examples
=> update number of qubits for H1-2 and add H2-1 targets in Quantinuum hello,world examples

samples/azure-quantum/CONTRIBUTING.md, samples/azure-quantum/grover/README.md, samples/azure-quantum/hello-world/HW-rigetti-qiskit.ipynb, samples/azure-quantum/hidden-shift/README.md, samples/azure-quantum/hidden-shift/hidden-shift.ipynb, samples/azure-quantum/ising-model/README.md, samples/azure-quantum/parallel-qrng/README.md, samples/azure-quantum/teleport/README.md
This PR removes references related to QIO (which has been deprecated) from the Quantum Samples.
Note that the Python SDK API documentation currently has an "optimization-" prefix in the URL:
https://learn.microsoft.com/azure/quantum/optimization-workspace
I'm investigating the cause of it and after fixing the URL, I'll create another PR to update the links to that page.
=> Remove QIO references from the Quantum Samples

samples/azure-quantum/resource-estimation/advanced-estimation.ipynb
The `azure_quantum` API is recommended to use over the IQ# API, since it is general for all input. In this PR, we change the advanced estimation notebook to use this API.
=> Update Advanced Estimation RE notebook to use azure_quantum API
