microsoft/Quantum

Microsoft.Quantum.Canon/Combinators/Bind.qs

This fixes the problems discussed in
https://quantum.uservoice.com/forums/906952-libraries/suggestions/33329446-bug-in-bindaimpl-adjoint-part
and
https://quantum.uservoice.com/forums/906097-general-ideas-and-feature-requests/suggestions/33329623-bug-in-bindaimpl-body-part

Fixes bug in BindAImpl

---

.travis.yml
README.md

Build status will be available at: https://travis-ci.org/Microsoft/Quantum.svg?branch=master

Creating .travis.yml to integrate with http://travis-ci.rg/

---

LibraryTests/CombinatorTests.qs
Microsoft.Quantum.Canon/Combinators/Compose.qs

This is a fairly minor PR, adding a new `Compose` function to represent the composition of two other functions.

Added a new Compose function.

---

.travis.yml
LibraryTests/CombinatorTests.qs
Microsoft.Quantum.Canon/Combinators/Bind.qs
Samples/H2SimulationGUI/package-lock.json
Samples/H2SimulationGUI/package.json

This PR inlines BindA to match the implementation of BindC and BindCA, as well as adds a unit test to guard against bugs that affect the body of BindA but not its adjoint body.

Inline BindA and improve unit testing.

---

LibraryTests/QuantumPhaseEstimationTests.qs
Microsoft.Quantum.Canon/PhaseEstimation/Quantum.qs

Fix Quantum Phase Estimation algorithm (QFT to Inverse QFT) and add a simple unit test

Fix quantum phase estimation

---

Interoperability/python/packages.config
LibraryTests/LibraryTests.csproj
Microsoft.Quantum.Canon/Microsoft.Quantum.Canon.csproj
Samples/AdiabaticIsing/AdiabaticIsingSample.csproj
Samples/BitFlipCode/BitFlipCode.csproj
Samples/DatabaseSearch/DatabaseSearchSample.csproj
Samples/H2SimulationCmdLine/H2SimulationSampleCmdLine.csproj
Samples/H2SimulationGUI/H2SimulationGUI.csproj
Samples/HubbardSimulation/HubbardSimulationSample.csproj
Samples/IntegerFactorization/IntegerFactorization.csproj
Samples/IsingGenerators/IsingGeneratorsSample.csproj
Samples/IsingPhaseEstimation/IsingPhaseEstimationSample.csproj
Samples/IsingTrotterEvolution/IsingTrotterSample.csproj
Samples/Measurement/Measurement.csproj
Samples/OpenQasm/OpenQasm.csproj
Samples/PhaseEstimation/PhaseEstimationSample.csproj
Samples/PythonInterop/PythonInterop.csproj
Samples/PythonInterop/environment.yml
Samples/PythonInterop/tomography-sample.ipynb
Samples/Qiskit/Qiskit.csproj
Samples/ReversibleLogicSynthesis/ReversibleLogicSynthesis.csproj
Samples/SimpleAlgorithms/SimpleAlgorithms.csproj
Samples/SimpleIsing/SimpleIsingSample.csproj
Samples/Teleportation/TeleportationSample.csproj
Samples/UnitTesting/Microsoft.Quantum.Canon.Tests.csproj

Creating pull request with new QDK version that fixes #48 (qsharp compilation fails if user name contains a blank space)

update qdk version

---

Interoperability/python/packages.config
LibraryTests/LibraryTests.csproj
Microsoft.Quantum.Canon/Microsoft.Quantum.Canon.csproj
Samples/AdiabaticIsing/AdiabaticIsingSample.csproj
Samples/BitFlipCode/BitFlipCode.csproj
Samples/DatabaseSearch/DatabaseSearchSample.csproj
Samples/H2SimulationCmdLine/H2SimulationSampleCmdLine.csproj
Samples/H2SimulationGUI/H2SimulationGUI.csproj
Samples/HubbardSimulation/HubbardSimulationSample.csproj
Samples/IntegerFactorization/IntegerFactorization.csproj
Samples/IsingGenerators/IsingGeneratorsSample.csproj
Samples/IsingPhaseEstimation/IsingPhaseEstimationSample.csproj
Samples/IsingTrotterEvolution/IsingTrotterSample.csproj
Samples/Measurement/Measurement.csproj
Samples/OpenQasm/OpenQasm.csproj
Samples/PhaseEstimation/PhaseEstimationSample.csproj
Samples/PythonInterop/PythonInterop.csproj
Samples/PythonInterop/environment.yml
Samples/PythonInterop/tomography-sample.ipynb
Samples/Qiskit/Qiskit.csproj
Samples/ReversibleLogicSynthesis/ReversibleLogicSynthesis.csproj
Samples/SimpleAlgorithms/SimpleAlgorithms.csproj
Samples/SimpleIsing/SimpleIsingSample.csproj
Samples/Teleportation/TeleportationSample.csproj
Samples/UnitTesting/Microsoft.Quantum.Canon.Tests.csproj

This one does actually fix the user's name with blank space problem (#48). Sigh.

Updating to latest qdk version.

---

.travis.yml
LibraryTests/LibraryTests.csproj
Samples/H2SimulationGUI/H2SimulationGUI.csproj
Samples/UnitTesting/Microsoft.Quantum.Canon.Tests.csproj

Testing a number of hypothesis of #66

Workaround for travis environment for suspected OpenMP concurrency bug on ubuntu 14.04

---

Interoperability/python/packages.config
LibraryTests/LibraryTests.csproj
Microsoft.Quantum.Canon/Microsoft.Quantum.Canon.csproj
Samples/AdiabaticIsing/AdiabaticIsingSample.csproj
Samples/BitFlipCode/BitFlipCode.csproj
Samples/DatabaseSearch/DatabaseSearchSample.csproj
Samples/H2SimulationCmdLine/H2SimulationSampleCmdLine.csproj
Samples/H2SimulationGUI/H2SimulationGUI.csproj
Samples/HubbardSimulation/HubbardSimulationSample.csproj
Samples/IntegerFactorization/IntegerFactorization.csproj
Samples/IsingGenerators/IsingGeneratorsSample.csproj
Samples/IsingPhaseEstimation/IsingPhaseEstimationSample.csproj
Samples/IsingTrotterEvolution/IsingTrotterSample.csproj
Samples/Measurement/Measurement.csproj
Samples/OpenQasm/OpenQasm.csproj
Samples/PhaseEstimation/PhaseEstimationSample.csproj
Samples/PythonInterop/PythonInterop.csproj
Samples/PythonInterop/environment.yml
Samples/Qiskit/Qiskit.csproj
Samples/ReversibleLogicSynthesis/ReversibleLogicSynthesis.csproj
Samples/SimpleAlgorithms/SimpleAlgorithms.csproj
Samples/SimpleIsing/SimpleIsingSample.csproj
Samples/Teleportation/TeleportationSample.csproj
Samples/UnitTesting/Microsoft.Quantum.Canon.Tests.csproj

Updating Libraries to latest QDK.

Updating to 0.2.1809.701

---

Samples/src/Arithmetic/Adder Example.ipynb

This adds a call to `%version` to the arithmetic sample notebook.

Add version information to arithmetic sample notebook.

---

Samples/src/Teleportation/Notebook.ipynb

Fixes bug reported by @jgukelberger.

Fix bug in teleport sample.

---

Chemistry/CreateHubbardHamiltonian/App.config
Chemistry/CreateHubbardHamiltonian/README.md

This PR updates the description of the CreateHubbardHamiltonian sample to fix #127.

Fixes #127.

---

careers.md

Jhenshaw patch 1

---

careers.md

We've hired into this position.

Removed senior outreach PM position

---

careers.md

Wrapping up interviews and extending an offer to a great candidate.

Removed the customer engagement PM position

---

samples/runtime/oracle-emulation/PermutationOracle.cs

Contributing: Fix a typo

---

samples/machine-learning/half-moons/HalfMoons.csproj
samples/machine-learning/half-moons/Training.qs
samples/machine-learning/wine/Training.qs
samples/machine-learning/wine/Wine.csproj

This PR updates the half-moon and wine samples to use the changes in microsoft/QuantumLibraries#220.

Update QML samples to use final API

---

samples/interoperability/fsharp/README.md

Also, I cannot find the solution file for Fsharp in the sample.

Wrong file reference (?) in F# sample

---

samples/interoperability/fsharp/Quantum_Fsharp.sln

As @geduardo pointed out in #328, the instructions for the sample mention .sln file which does not exist.

Add .sln file to F# interoperability sample

---

.vscode/extensions.json

The extension name changed, so I updated the file with the recommendations.

Update extension identifier for C# extension

---

samples/algorithms/database-search/DatabaseSearch.qs
samples/algorithms/database-search/README.md

This PR fixes one typo, one reference to library function, and some recommendations to Markdown formatting.

Small fixes to database example

---

samples/tests/sample-tests/SampleTests.csproj

This project is already using the Quantum SDK, these are superfluos

Removing references to Microsoft Quantum Development Kit

---

.vscode/settings.json
Build/images/samples/Dockerfile
samples/error-correction/bit-flip-code/BitFlipCode.qs

Miscellaneous bugfixes:
* Fixes #400 
* fixes outdated URL in sample docstring
* adds pythonPath to vscode settings (for seamless use in Codespaces or Docker container)

Misc bugfixes: qsharp version in Dockerfile, outdated URL, add pythonPath in settings.json

---

samples/simulation/ising/simple/Program.qs
samples/simulation/ising/simple/SimpleIsing.qs

Added the coupling terms as an input parameter, implemented in Q#

Sample enhancement: Add options for tweaking site-to-site coupling parameters for Ising lattice

---

samples/algorithms/sudoku-grover/ColoringGroverWithConstraints.qs
samples/algorithms/sudoku-grover/README.md

Fix README formatting
Also, fix the project filename in the README
Also update the formatting in comments ColoringGroverWithConstraints.qs

fix Sudoku README

---

binder-index.md
samples/diagnostics/dumping/Dumping States and Operations.ipynb
samples/diagnostics/dumping/README.md
samples/diagnostics/facts-and-assertions/Facts and Assertions.ipynb
samples/diagnostics/facts-and-assertions/README.md

This PR adds two new samples, one on dumping states and operations, the other on using facts and assertions.

Added two new diagnostics samples.

---

samples/chemistry/LithiumHydrideGUI/Program.cs
samples/chemistry/LithiumHydrideGUI/package-lock.json

Updated packages because of a low security issue in init (dependabot #446).
Trying to test the application on mac highlighted a windows style path, so changed that one to an os invariant one.

Updated packages of Lithdemo and removed Windows dependency

---

build.yml
samples/chemistry/MolecularHydrogenGUI/package-lock.json
samples/chemistry/MolecularHydrogenGUI/package.json
samples/runtime/state-visualizer/package-lock.json
samples/runtime/state-visualizer/package.json
samples/simulation/h2/gui/package-lock.json
samples/simulation/h2/gui/package.json

Enables the component governance build task, schedules weekly builds, and resolves current component governance flags.

Enable component governance

---

Build/images/samples/Dockerfile
binder-index.md
samples/azure-quantum/README.md
samples/azure-quantum/azure-quantum.sln
samples/azure-quantum/grover/Grover.csproj
samples/azure-quantum/grover/README.md
samples/azure-quantum/grover/Reflections.qs
samples/azure-quantum/grover/SimpleGrover.qs
samples/azure-quantum/hidden-shift/HiddenShift.csproj
samples/azure-quantum/hidden-shift/HiddenShift.qs
samples/azure-quantum/hidden-shift/README.md
samples/azure-quantum/ising-model/IsingModel.csproj
samples/azure-quantum/ising-model/IsingModel.qs
samples/azure-quantum/ising-model/README.md
samples/azure-quantum/parallel-qrng/ParallelQrng.csproj
samples/azure-quantum/parallel-qrng/ParallelQrng.ipynb
samples/azure-quantum/parallel-qrng/ParallelQrng.qs
samples/azure-quantum/parallel-qrng/README.md
samples/azure-quantum/parallel-qrng/parallel_qrng.py
samples/azure-quantum/teleport/README.md
samples/azure-quantum/teleport/Teleport.csproj
samples/azure-quantum/teleport/Teleport.qs
samples/chemistry/MolecularHydrogen/HydrogenSimulation.qs
samples/chemistry/SimulateHubbardHamiltonian/HubbardSimulation.qs

This PR adds new samples for using Q# with the Azure Quantum service, and updates the Binder / Codespaces configuration to support these new samples.

New samples for Q# + Azure Quantum service.

---

samples/algorithms/integer-factorization/FGResourcesEstimator.cs
samples/algorithms/integer-factorization/FlameGraphCounter.cs
samples/algorithms/integer-factorization/FlameGraphResourcesEstimator.cs
samples/algorithms/integer-factorization/Program.cs
samples/algorithms/integer-factorization/README.md

Addition of a visualize method to Program.cs
To generate a flame graph, follow these steps:
1. Run Program.cs with the `visualize` option by specifying the generator and the resource (more information in the help text) to be visualized. Save the output in a file.
2. Use [flamegraph.pl](https://github.com/brendangregg/FlameGraph#3-flamegraphpl) with the above file to generate an svg of the flame graph.

Implement flame graph visualization

---

samples/getting-started/intro-to-iqsharp/Notebook.ipynb

Made correction to a repetitive operator name in jupyter notebook.

Corrrect operation name in Notebook.ipynb

---

samples/getting-started/qrng/README.md
samples/getting-started/qrng/host.py

Fixes #492. This PR adds a host.py Python program to run the random number generator from Python.

Create host.py example for qrng

---

.gitignore
Build/QIR_validation.ps1
Build/build.ps1
Build/validate-qir.ps1

Moving the QIR validation out of the build script and into its own separate script. This script may be run by itself manually, but its ultimate purpose is to be run as part of the QDK's CI validation steps.
Several Samples are currently in a good state to be compiled with QIR, have the resulting dll compiled further into an executable, and have that executable run to test that the QIR is working as intended. Many samples have some qualities about them that make them not compatible for this process as of yet. The purpose of this PR is not to make all the samples compatible for QIR validation but to set up a framework for QIR validation using some of the already-compatible samples.

QIR Validation Script

---

Build/test.ps1

This adds an integration test for the auto substitution sample to check the rewrite step in builds.

Integration test for AutoSubstitution rewrite step

---

samples/runtime/autosubstitution/AutoSubstitution.csproj

Sdk and package version differ

Fix version inconsistency in AutoSubstitution sample

---

cspell.json
samples/azure-quantum/grover/Grover.ipynb
samples/azure-quantum/grover/README.md

Add a notebook based on the existing Grover's search sample.

Add a notebook to the Grover's search sample

---

samples/algorithms/integer-factorization/IntegerFactorization.csproj
samples/algorithms/integer-factorization/Program.cs
samples/algorithms/integer-factorization/QuantumVizCounter.cs
samples/algorithms/integer-factorization/QuantumVizEstimator.cs
samples/algorithms/integer-factorization/README.md

This extends the integer factorization sample to produce JSON output for quantum-viz.js, incl. the hierarchy of the call stack and annotated resource estimates to each operation in the call stack.

Resources estimation with quantum-viz.js

---

samples/azure-quantum/hello-world/HW-honewell-cirq.ipynb
samples/azure-quantum/hello-world/HW-honeywell-qiskit.ipynb
samples/azure-quantum/hello-world/HW-honeywell-qsharp.ipynb
samples/azure-quantum/hello-world/HW-ionq-cirq.ipynb
samples/azure-quantum/hello-world/HW-ionq-qiskit.ipynb
samples/azure-quantum/hello-world/HW-ionq-qsharp.ipynb

Create QC hello world samples to be displayed in the sample gallery.

Add hello world samples

---

Build/images/samples/Dockerfile

Upgrade Powershell version for security compliance.

Update Powershell version

---

samples/azure-quantum/grover/Grover.csproj
samples/azure-quantum/grover/Grover.ipynb
samples/azure-quantum/grover/README.md

Add Grover sample to feature/samples-gallery branch from main

Sync Grover sample to feature branch

---

samples/azure-quantum/hello-world/HW-honeywell-cirq.ipynb
samples/azure-quantum/hello-world/HW-honeywell-qiskit.ipynb
samples/azure-quantum/hello-world/HW-honeywell-qsharp.ipynb
samples/azure-quantum/hello-world/HW-ionq-cirq.ipynb
samples/azure-quantum/hello-world/HW-ionq-qiskit.ipynb
samples/azure-quantum/hello-world/HW-ionq-qsharp.ipynb

Note that the job costs documentation page is a broken link but will point to this page once the corresponding PR is merged: https://review.docs.microsoft.com/en-us/azure/quantum/azure-quantum-job-costs?branch=pr-en-us-721

Add cost estimation cell + link to docs to hello world notebooks in sample gallery + plotting fix for Q# notebooks

---

samples/azure-quantum/grover/Grover.csproj
samples/azure-quantum/grover/README.md
samples/azure-quantum/hello-world/HW-quantinuum-cirq.ipynb
samples/azure-quantum/hello-world/HW-quantinuum-qiskit.ipynb
samples/azure-quantum/hello-world/HW-quantinuum-qsharp.ipynb
samples/azure-quantum/hidden-shift/HiddenShift.csproj
samples/azure-quantum/hidden-shift/README.md
samples/azure-quantum/ising-model/IsingModel.csproj
samples/azure-quantum/ising-model/README.md
samples/azure-quantum/parallel-qrng/ParallelQrng.csproj
samples/azure-quantum/parallel-qrng/README.md
samples/azure-quantum/teleport/README.md
samples/azure-quantum/teleport/Teleport.csproj

This PR contains update to the jupyter notebook samples for the quantinuum rebrand

Quantinuum rebrand

---

samples/azure-quantum/hello-world/HW-ionq-cirq.ipynb
samples/azure-quantum/hello-world/HW-ionq-qiskit.ipynb
samples/azure-quantum/hello-world/HW-ionq-qsharp.ipynb
samples/azure-quantum/hello-world/HW-quantinuum-cirq.ipynb
samples/azure-quantum/hello-world/HW-quantinuum-qiskit.ipynb
samples/azure-quantum/hello-world/HW-quantinuum-qsharp.ipynb

Removes the empty cell at the bottom of the hello world notebooks.

Remove empty cells

---

samples/getting-started/simulation/LargeSimulation.ipynb

AQ renderer does not handle Esc-sequences properly. Have to change in AQ gallery branch. For consistency changing in main too (to be cherry-picked to AQ gallery branch).

AQ gallery renderer fix.

---

.github/workflows/hosted-notebook-samples-check.yml

I believe this needs to be merged back to the feature branch for the trigger to execute.

Bring in workflow to check samples

---

.github/workflows/hosted-notebook-samples-check.yml

The documentation for the pipeline task is not quite right; apparently we need to use version 1.2 to pass variables.
Also had to experiment quite a bit with the syntax for passing the variables themselves (hence all the commits). In its current state, the variables get passed correctly.

Update task version and pass all variables

---

Build/images/samples/Dockerfile

Update to latest iqsharp-base image to pick up Linux security patches.

Update to latest iqsharp-base version

---

samples/azure-quantum/hello-world/HW-ionq-cirq.ipynb
samples/azure-quantum/hello-world/HW-ionq-qiskit.ipynb
samples/azure-quantum/hello-world/HW-ionq-qsharp.ipynb
samples/azure-quantum/hello-world/HW-quantinuum-cirq.ipynb
samples/azure-quantum/hello-world/HW-quantinuum-qiskit.ipynb
samples/azure-quantum/hello-world/HW-quantinuum-qsharp.ipynb

(My kernel seems to be older than the one used when creating these samples, so it did some automatic changes during editing, including removing cell ids and changing version and display names. If the gallery is sensitive to this, you can open the notebooks in the latest editor and re-save them, and these fields will come back :-) )

Fix table rendering in Hello World samples

---

samples/algorithms/integer-factorization/README.md

I have added to the README to include prereqs and additional run examples.

expand run instructions in integer factorization sample

---

Build/images/samples/Dockerfile

Update the version to pull in security patches.

Update iqsharp-base version

---

samples/azure-quantum/hello-world/HW-rigetti-qiskit.ipynb
samples/azure-quantum/hello-world/HW-rigetti-qsharp.ipynb
samples/azure-quantum/hidden-shift-gallery/hidden-shift.ipynb

Currently a work in progress - these are the hello world samples for Rigetti that we will surface in the sample gallery.
Open questions:
- How many qubits are available in the QVM?
- Wording in the target description - appropriate?
- What pricing do we anticipate? Will these notebooks run for free?

Rigetti Hello World samples

---

Build/test.ps1

This PR makes more verbose logging available from test.ps1.

Enable verbose logging from test.ps1.

---

.github/workflows/hosted-notebook-samples-check.yml
samples/algorithms/noisy-dj/Deutsch–Jozsa with Noise.ipynb

The workflow file changes in this PR are due to an issue with samples that have spaces in the names or special characters (like the long dash).

Update Deutsch–Jozsa with Noise.ipynb

---

samples/azure-quantum/hello-world/HW-ionq-cirq.ipynb
samples/azure-quantum/hello-world/HW-ionq-qiskit.ipynb
samples/azure-quantum/hello-world/HW-ionq-qsharp.ipynb

Add aria to targets on ionq hello world samples

Add aria to hello world samples

---

samples/azure-quantum/hello-world/HW-rigetti-qiskit.ipynb
samples/azure-quantum/hello-world/HW-rigetti-qsharp.ipynb

Add m2 target to Rigetti hello world samples.

Add m2 target to hello world

---

samples/azure-quantum/hello-world/HW-rigetti-qiskit.ipynb
samples/azure-quantum/hello-world/HW-rigetti-qsharp.ipynb

Update Rigetti "Hello World" samples to include M2.

Update Rigetti "Hello World" samples

---

samples/algorithms/sudoku-grover/ColoringGroverWithConstraints.qs

The input and output documentation above `ApplyPhaseOracle` did not match the function and have been reworded

Fix documentation of `ApplyPhaseOracle` in sudoku-grover sample

---

samples/qir/oracle-generator/README.md

Related PRs:
https://github.com/microsoft/qsharp-compiler/pull/1559
https://github.com/microsoft/Quantum/pull/720

Working around the out-of-date links.

---

samples/azure-quantum/hello-world/HW-ionq-cirq.ipynb
samples/azure-quantum/hello-world/HW-ionq-qiskit.ipynb
samples/azure-quantum/hello-world/HW-ionq-qsharp.ipynb

* Add aria to hello world samples

Add aria to hello world samples (#709)

---

samples/qir/oracle-generator/qsharp/project.csproj

This PR addresses a couple of errors from PR #726

Fixing samples after update to 0.26.233415

---

samples/azure-quantum/resource-estimation/advanced-estimation.ipynb
samples/azure-quantum/resource-estimation/estimation-dynamics.ipynb
samples/azure-quantum/resource-estimation/estimation-qsharp.ipynb

- Removed hu-hu language code from MultiplyI links, so it adjusts to user's language preference.
- Added imports for display, so that intellisense does not complain

Fix estimation MultiplyI links and intellisense for display

---

Build/test.ps1
samples/azure-quantum/grover/Grover.ipynb
samples/azure-quantum/parallel-qrng/ParallelQrng.ipynb
samples/azure-quantum/parallel-qrng/ParallelQrng.qs
samples/azure-quantum/parallel-qrng/parallel_qrng.py

Fix samples to enable them to run on Rigetti targets.

Fix samples to enable them to run on Rigetti targets

---

binder-index.md
samples/azure-quantum/utilities/README.md
samples/azure-quantum/utilities/storage-data-management.ipynb

This sample shows you how to connect and use Azure Quantum with external datasources such as [Azure Blob Storage](https://learn.microsoft.com/azure/storage/blobs/storage-blobs-introduction). In particular, how to connect to the attached blob storage account associated with each AQ Workspace. Also shows how to load files from a URL and work with local storage.

Adding storage sample for gallery

---

README.md
samples/azure-quantum/resource-estimation/advanced-estimation.ipynb
samples/azure-quantum/resource-estimation/estimation-qir.ipynb
samples/azure-quantum/resource-estimation/estimation-qsharp.ipynb

The notebooks can now make use of Q# input arguments.

Update resource estimation notebooks to use new features

---

samples/azure-quantum/adapting-code/README.md
samples/azure-quantum/adapting-code/adapting-qiskit-sample.ipynb

If you have some experience with quantum computing or are just starting, it is likely that you will use some samples from Qiskit.org. This Jupyter notebook walks you through four simple steps to adapt an existing Qiskit sample to run against any of the Azure Quantum back-ends.

Adapting downloaded Qiskit sample

---

samples/diagnostics/unit-testing/UnitTesting.csproj
samples/runtime/qpic-simulator/host/host.csproj
samples/tests/sample-tests/SampleTests.csproj

**Multi-repo PR:**
[Q#C](https://github.com/microsoft/qsharp-compiler/pull/1607), [Q#RT](https://github.com/microsoft/qsharp-runtime/pull/1128), [iQ#](https://github.com/microsoft/iqsharp/pull/770), [Katas](https://github.com/microsoft/QuantumKatas/pull/873), [QLib](https://github.com/microsoft/QuantumLibraries/pull/657), [Q](https://github.com/microsoft/Quantum/pull/781), [Q-NC](https://github.com/microsoft/Quantum-NC/pull/85), private repo, QDK.
DevOps items 48477, 48480, 48478.

Upgraded "Microsoft.NET.Test.Sdk" and "xunit.runner.visualstudio".

---

samples/azure-quantum/utilities/storage-data-management.ipynb

Simplify sample to not use sas uri parsing

Remove sas uri parsing from storage sample

---

.github/workflows/prebuild-docker.yml
.github/workflows/test-docker-image-build.yml
Build/images/samples/Dockerfile

Fixed the Docker image.

---

samples/algorithms/integer-factorization/FlameGraphResourcesEstimator.cs
samples/algorithms/integer-factorization/Program.cs
samples/algorithms/integer-factorization/QuantumVizEstimator.cs

Removed use of deprecated ResourcesEstimator class.

Removing local resources estimator

---

samples/azure-quantum/resource-estimation/advanced-estimation.ipynb
samples/azure-quantum/resource-estimation/estimation-chemistry.ipynb
samples/azure-quantum/resource-estimation/estimation-factoring.ipynb
samples/azure-quantum/resource-estimation/estimation-qir.ipynb

This can only be merged after the `feature/re-client-api` branch has been merged into `main` in microsoft/qdk-python.

Update RE notebooks for QIR based API

---

Build/images/samples/Dockerfile

Update PowerShell version installed in the Samples image to use PowerShell 7.2.11.

Update PowerShell Installed to 7.2.11

---

NuGet.config

Group PR.
QDK (368)
* [IQ#](https://github.com/microsoft/iqsharp/pull/800)
* [Q# Compiler](https://github.com/microsoft/qsharp-compiler/pull/1621)
* [qsharp-runtime](https://github.com/microsoft/qsharp-runtime/pull/1148)
* [Quantum](https://github.com/microsoft/Quantum/pull/815)
* [Quantum-NC](https://github.com/microsoft/Quantum-NC/pull/91)
* [QuantumKatas](https://github.com/microsoft/QuantumKatas/pull/888)
* [QuantumLibraries](https://github.com/microsoft/QuantumLibraries/pull/679)
* private repo (19643)
* [qdk-python](https://github.com/microsoft/qdk-python/pull/488)

 Fixing CI

---

samples/azure-quantum/repeat-until-success/README.md
samples/azure-quantum/repeat-until-success/repeat-until-success.ipynb

This adds a notebook with a subset of the RUS experiment on Quanitnuum to allow users to repeat this experiment on their own as a hosted notebook.

Add RUS Azure Quantum notebook sample
